# Generated by Django 4.1 on 2022-12-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribuidoras', models.CharField(choices=[('AME', 'AME'), ('Boa Vista', 'Boa Vista'), ('CASTRO - DIS', 'CASTRO - DIS'), ('CEA', 'CEA'), ('CEBDIS', 'CEBDIS'), ('CEDRAP', 'CEDRAP'), ('CEDRI', 'CEDRI'), ('CEEE-D', 'CEEE-D'), ('CEGERO', 'CEGERO'), ('CEJAMA', 'CEJAMA'), ('CELESC-DIS', 'CELESC-DIS'), ('CELETRO', 'CELETRO'), ('CELG-D', 'CELG-D'), ('CELPE', 'CELPE'), ('CEMIG-D', 'CEMIG-D'), ('CEMIRIM', 'CEMIRIM'), ('CEPRAG', 'CEPRAG'), ('CERAÇÁ', 'CERAÇÁ'), ('CERAL ANITÁPOLIS', 'CERAL ANITÁPOLIS'), ('CERAL ARAPOTI', 'CERAL ARAPOTI'), ('CERAL ARARUAMA', 'CERAL ARARUAMA'), ('CERBRANORTE', 'CERBRANORTE'), ('CERCI', 'CERCI'), ('CERCOS', 'CERCOS'), ('CEREJ', 'CEREJ'), ('CERES', 'CERES'), ('CERFOX', 'CERFOX'), ('CERGAL', 'CERGAL'), ('CERGAPA', 'CERGAPA'), ('CERGRAL', 'CERGRAL'), ('CERILUZ', 'CERILUZ'), ('CERIM', 'CERIM'), ('CERIPA', 'CERIPA'), ('CERIS', 'CERIS'), ('CERMC', 'CERMC'), ('CERMISSÕES', 'CERMISSÕES'), ('CERMOFUL', 'CERMOFUL'), ('CERNHE', 'CERNHE'), ('CERON', 'CERON'), ('CERPALO', 'CERPALO'), ('CERPRO', 'CERPRO'), ('CERR', 'CERR'), ('CERRP', 'CERRP'), ('CERSAD DISTRIBUIDORA', 'CERSAD DISTRIBUIDORA'), ('CERSUL', 'CERSUL'), ('CERTAJA', 'CERTAJA'), ('CERTEL ENERGIA', 'CERTEL ENERGIA'), ('CERTHIL', 'CERTHIL'), ('CERTREL', 'CERTREL'), ('CERVAM', 'CERVAM'), ('CETRIL', 'CETRIL'), ('CFLO', 'CFLO'), ('CHESP', 'CHESP'), ('CNEE', 'CNEE'), ('COCEL', 'COCEL'), ('CODESAM', 'CODESAM'), ('COELBA', 'COELBA'), ('COOPERA', 'COOPERA'), ('COOPERALIANÇA', 'COOPERALIANÇA'), ('COOPERCOCAL', 'COOPERCOCAL'), ('COOPERLUZ', 'COOPERLUZ'), ('COOPERMILA', 'COOPERMILA'), ('COOPERNORTE', 'COOPERNORTE'), ('COOPERSUL', 'COOPERSUL'), ('COOPERZEM', 'COOPERZEM'), ('COORSEL', 'COORSEL'), ('COPEL-DIS', 'COPEL-DIS'), ('COPREL', 'COPREL'), ('COSERN', 'COSERN'), ('CPFL Jaguari', 'CPFL Jaguari'), ('CPFL Leste Paulista', 'CPFL Leste Paulista'), ('CPFL Mococa', 'CPFL Mococa'), ('CPFL Santa Cruz', 'CPFL Santa Cruz'), ('CPFL Sul Paulista', 'CPFL Sul Paulista'), ('CPFL- PIRATININGA', 'CPFL- PIRATININGA'), ('CPFL-PAULISTA', 'CPFL-PAULISTA'), ('CRELUZ-D', 'CRELUZ-D'), ('CRERAL', 'CRERAL'), ('DCELT', 'DCELT'), ('DEMEI', 'DEMEI'), ('DMED', 'DMED'), ('EBO', 'EBO'), ('EDEVP', 'EDEVP'), ('EDP ES', 'EDP ES'), ('EDP SP', 'EDP SP'), ('EEB', 'EEB'), ('EFLJC', 'EFLJC'), ('EFLUL', 'EFLUL'), ('ELEKTRO', 'ELEKTRO'), ('ELETROACRE', 'ELETROACRE'), ('ELETROCAR', 'ELETROCAR'), ('ELETROPAULO', 'ELETROPAULO'), ('ELFSM', 'ELFSM'), ('EMG', 'EMG'), ('EMS', 'EMS'), ('EMT', 'EMT'), ('ENEL CE', 'ENEL CE'), ('ENEL RJ', 'ENEL RJ'), ('ENF', 'ENF'), ('EPB', 'EPB'), ('Equatorial AL', 'Equatorial AL'), ('Equatorial MA', 'Equatorial MA'), ('Equatorial PA', 'Equatorial PA'), ('Equatorial PI', 'Equatorial PI'), ('ESE', 'ESE'), ('ESS', 'ESS'), ('ETO', 'ETO'), ('FORCEL', 'FORCEL'), ('HIDROPAN', 'HIDROPAN'), ('LIGHT', 'LIGHT'), ('MUXENERGIA', 'MUXENERGIA'), ('RGE', 'RGE'), ('RGE SUL', 'RGE SUL'), ('SULGIPE', 'SULGIPE'), ('UHENPAL', 'UHENPAL')], default=None, max_length=150)),
                ('grupo_tarifario', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A3a', 'A3a'), ('A4', 'A4'), ('A4a', 'A4a'), ('A4b', 'A4b'), ('AS', 'AS'), ('B', 'B'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4')], default=None, max_length=20)),
                ('consumo_ponta', models.DecimalField(decimal_places=5, max_digits=50)),
                ('consumo_fora_ponta', models.DecimalField(decimal_places=5, max_digits=50)),
                ('demanda_contratada', models.DecimalField(decimal_places=5, max_digits=50)),
                ('nome_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
